# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PBS_Dynamic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoapReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseID', models.CharField(db_index=True, max_length=32, verbose_name='\u5173\u8054\u4e3b\u7528\u4f8bID')),
                ('ClickExecutionTime', models.DateTimeField(db_index=True, verbose_name='\u70b9\u51fb\u6267\u884c\u52a8\u4f5c\u7684\u65f6\u95f4')),
                ('APIResult', models.TextField(blank=True, null=True, verbose_name='API\u7ed3\u679c')),
                ('ExecutionTime', models.DateTimeField(null=True, verbose_name='\u7528\u4f8b\u6267\u884c\u7684\u65f6\u95f4')),
                ('Environment', models.CharField(db_index=True, max_length=10, verbose_name='\u73af\u5883')),
                ('Status', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u72b6\u6001')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoapSubReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseID', models.CharField(db_index=True, max_length=32, verbose_name='\u5173\u8054\u4e3b\u7528\u4f8bID')),
                ('ClickExecutionTime', models.DateTimeField(db_index=True, verbose_name='\u70b9\u51fb\u6267\u884c\u52a8\u4f5c\u7684\u65f6\u95f4')),
                ('APIResult', models.TextField(blank=True, null=True, verbose_name='API\u7ed3\u679c')),
                ('ExecutionTime', models.DateTimeField(null=True, verbose_name='\u7528\u4f8b\u6267\u884c\u7684\u65f6\u95f4')),
                ('Environment', models.CharField(db_index=True, max_length=10, verbose_name='\u73af\u5883')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SOAPSubTestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(blank=True, max_length=256, verbose_name='\u7cfb\u7edf')),
                ('Description', models.CharField(max_length=256, verbose_name='\u6d4b\u8bd5\u7528\u4f8b\u63cf\u8ff0')),
                ('Method', models.CharField(max_length=10, verbose_name='\u65b9\u6cd5')),
                ('Headers', models.TextField(verbose_name='\u4fe1\u606f\u5934')),
                ('BodyValues', models.TextField(blank=True, null=True, verbose_name='Body\u503c')),
                ('APIResult', models.TextField(blank=True, null=True, verbose_name='API\u7ed3\u679c')),
                ('ExecutionTime', models.DateTimeField(blank=True, null=True, verbose_name='\u7528\u4f8b\u6267\u884c\u65f6\u95f4')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u7528\u4f8b\u521b\u5efa\u65f6\u95f4')),
                ('UseTime', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u63a5\u53e3\u6d88\u8017\u65f6\u95f4(s)')),
                ('SetupType', models.CharField(max_length=10, verbose_name='Setup\u7c7b\u578b')),
                ('SetupIndex', models.CharField(blank=True, max_length=32, verbose_name='\u5173\u8054\u4e3b\u7528\u4f8bSetup\u6b65\u9aa4')),
                ('CaseID', models.CharField(blank=True, max_length=32, verbose_name='\u5173\u8054\u4e3b\u7528\u4f8bID')),
                ('DataBox', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u6570\u636e\u503c')),
                ('Host', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='PBS_Dynamic.SystemHost', verbose_name='HOST\u73af\u5883\u8def\u5f84')),
            ],
            options={
                'verbose_name': 'SubTestCase',
                'verbose_name_plural': '\u5b50\u6d4b\u8bd5\u7528\u4f8b',
            },
        ),
        migrations.CreateModel(
            name='SOAPTestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(blank=True, max_length=256, verbose_name='\u7cfb\u7edf')),
                ('Description', models.CharField(max_length=256, verbose_name='\u6d4b\u8bd5\u7528\u4f8b\u63cf\u8ff0')),
                ('Method', models.CharField(max_length=10, verbose_name='\u65b9\u6cd5')),
                ('Headers', models.TextField(verbose_name='\u4fe1\u606f\u5934')),
                ('BodyValues', models.TextField(blank=True, null=True, verbose_name='Body\u503c')),
                ('APIResult', models.TextField(blank=True, null=True, verbose_name='API\u7ed3\u679c')),
                ('ExecutionTime', models.DateTimeField(blank=True, null=True, verbose_name='\u7528\u4f8b\u6267\u884c\u65f6\u95f4')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u7528\u4f8b\u521b\u5efa\u65f6\u95f4')),
                ('UseTime', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u63a5\u53e3\u6d88\u8017\u65f6\u95f4(s)')),
                ('SetupStep', models.CharField(blank=True, max_length=256, verbose_name='Setup\u6b65\u9aa4')),
                ('Expect', models.CharField(max_length=2048, verbose_name='\u9884\u671f\u503c')),
                ('Status', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u72b6\u6001')),
                ('User', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u6267\u884c\u8005')),
                ('Editor', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u521b\u5efa/\u7f16\u8f91\u8005')),
                ('Host', models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.CASCADE, to='PBS_Dynamic.SystemHost', verbose_name='HOST\u73af\u5883\u8def\u5f84')),
            ],
            options={
                'verbose_name': 'SOAPTestCase',
                'verbose_name_plural': '\u4e3b\u6d4b\u8bd5\u7528\u4f8b',
            },
        ),
        migrations.AddField(
            model_name='soapsubreport',
            name='soapSubCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SOAP_API.SOAPSubTestCases'),
        ),
        migrations.AddField(
            model_name='soapreport',
            name='soapTestCase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SOAP_API.SOAPTestCases'),
        ),
    ]
